### ISSUE TITLE
Jade support?

### ISSUE THREAD

**Issue by comerc** [themeteorites/blaze-magic-events#3]
Please example!

**Comment by seeekr** [comment]
Yes, Jade is supported. Just translate the example to Jade and you'll be fine. Specifically:

`<button onclick={{sayHi}}>Say Hi!</button>`

turns into

`button(onclick=sayHi) Say Hi!`

The JavaScript code can stay as is.

**Comment by comerc** [comment]
But how to translate this code?

```
<button onclick={{say name "hi"}}>say "hi" (using args)</button>
```

**Comment by seeekr** [comment]
Like this:

```
button(onclick="{{say name 'hi'}}") say "hi" (using args)
```

The idea is that the meteor-jade compiler (at least when using mquandalle:jade, which is the only Jade package I've ever used with Meteor) just turns everything into Spacebars expressions anyway, and by using quotes and {{ }} you can just give it directly exactly what you want the Spacebars output to be. Hope that makes sense. Essentially you're writing a Spacebars expression there, so it won't even actually have to go through the Jade syntax/engine.
